field: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
fieldLayouts:
  e4993876-9970-4186-ba10-9efd312e8bd7:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 09b6e13d-5b43-4e45-b956-1532e3fc1e7d # Section heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d28fdaa9-47cc-460a-9718-ef9e4fa90325
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 45ee1d4e-96ee-4415-bd34-ad8dd562b918 # Image(s)
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: c6f320a6-dba6-4e17-b48a-7e524d040399
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 2362705b-9855-402e-8e77-df0481694d79 # Section background colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: aa0f1f30-9a7b-44df-9452-0d81bb4064cc
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 5cb66de2-c452-4b14-82c0-764660c36beb
        userCondition: null
fields:
  09b6e13d-5b43-4e45-b956-1532e3fc1e7d: # Section heading
    columnSuffix: pjvfobqg
    contentColumnType: text
    fieldGroup: null
    handle: sectionHeading
    instructions: null
    name: 'Section heading'
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: false
      columnType: null
      initialRows: 4
      multiline: false
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  45ee1d4e-96ee-4415-bd34-ad8dd562b918: # Image(s)
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: images
    instructions: 'Add a single image, 2 images side by side or 3+ images for a gallery carousel.'
    name: Image(s)
    searchable: false
    settings:
      allowSelfRelations: false
      allowSubfolders: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:b51c3bf7-bd4c-46f9-92d5-c548637e190a' # Images
      defaultUploadLocationSubpath: null
      localizeRelations: false
      maxRelations: null
      minRelations: null
      previewMode: full
      restrictFiles: false
      restrictLocation: false
      restrictedDefaultUploadSubpath: null
      restrictedLocationSource: 'volume:b51c3bf7-bd4c-46f9-92d5-c548637e190a' # Images
      restrictedLocationSubpath: null
      selectionCondition:
        __assoc__:
          -
            - elementType
            - craft\elements\Asset
          -
            - fieldContext
            - global
          -
            - class
            - craft\elements\conditions\assets\AssetCondition
      selectionLabel: null
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      source: null
      sources:
        - 'volume:b51c3bf7-bd4c-46f9-92d5-c548637e190a' # Images
      targetSiteId: null
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
  2362705b-9855-402e-8e77-df0481694d79: # Section background colour
    columnSuffix: mdqfsnkq
    contentColumnType: string
    fieldGroup: null
    handle: sectionBG
    instructions: null
    name: 'Section background colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - ''
        -
          __assoc__:
            -
              - label
              - Silver
            -
              - value
              - silver
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
handle: images
name: Image(s)
sortOrder: 3
