field: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
fieldLayouts:
  a0b73357-c352-4da0-a14f-23235c80fa59:
    tabs:
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: ee12cfc1-e007-4254-bc36-f5ff21ea00bd # Body
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f74bf4e6-380b-4ea6-851a-b17af44e7ecc
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4d75c350-59e2-4ecc-b469-bb97f6ff276d # Section background colour
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8d0b8dc-18cd-4c67-826b-f937995abcd5
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: 10a15281-2859-4325-96fa-26b23d4ebd52 # Text alignment
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d4825fdb-788a-4926-966b-55588e49ce19
            userCondition: null
            warning: null
            width: 50
        name: Content
        uid: 6b3c7060-eeb5-433e-9cd2-5fd0090f1e66
        userCondition: null
fields:
  4d75c350-59e2-4ecc-b469-bb97f6ff276d: # Section background colour
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: sectionBG
    instructions: null
    name: 'Section background colour'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - White
            -
              - value
              - white
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Silver
            -
              - value
              - silver
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\Dropdown
  10a15281-2859-4325-96fa-26b23d4ebd52: # Text alignment
    columnSuffix: jqdyptat
    contentColumnType: string
    fieldGroup: null
    handle: textAlign
    instructions: null
    name: 'Text alignment'
    searchable: false
    settings:
      options:
        -
          __assoc__:
            -
              - label
              - Left
            -
              - value
              - left
            -
              - default
              - '1'
        -
          __assoc__:
            -
              - label
              - Centre
            -
              - value
              - centre
            -
              - default
              - ''
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\RadioButtons
  ee12cfc1-e007-4254-bc36-f5ff21ea00bd: # Body
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: body
    instructions: null
    name: Body
    searchable: true
    settings:
      availableTransforms: ''
      availableVolumes: ''
      columnType: text
      configSelectionMode: choose
      defaultTransform: ''
      manualConfig: ''
      purifierConfig: null
      purifyHtml: true
      redactorConfig: MatrixBody.json
      removeEmptyTags: true
      removeInlineStyles: true
      removeNbsp: true
      showHtmlButtonForNonAdmins: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\redactor\Field
handle: text
name: Text
sortOrder: 1
