fieldLayouts:
  219cc855-2268-4bc0-8f1e-497f8a02c1a9:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            elementCondition: null
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e53abff-3c4f-48db-a9cf-8777bca2afe1
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 661f0cbe-8667-4984-aea8-55239d2f6e8e # Body builder
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 9f75574a-a555-4fb8-87cb-4c2aff1e8151
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 8e6842d0-a61a-4d89-9e15-1e2e63d36e30
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: f39fc309-38af-4102-a273-2f39c074cd50 # Banner title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a113de07-b776-478a-b4b9-22d903fd613d
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 4581a2fb-8ab7-44a1-a4ab-d85dfed32337 # Banner image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 861acff5-68ba-4a54-9009-cc0b94b02fc6
            userCondition: null
            warning: null
            width: 50
          -
            elementCondition: null
            fieldUid: fb2c7357-1d97-45f9-a8f4-c214dcea3154 # Banner size
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 63057182-74a2-4123-95d9-72e0646c0745
            userCondition: null
            warning: null
            width: 25
          -
            elementCondition: null
            fieldUid: 7ebfcde4-6eaf-43f9-b8d0-c36884f67bc0 # Banner overlay opacity
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5add5226-014e-46a7-8c03-ddb8ede44a8c
            userCondition: null
            warning: null
            width: 25
        name: Banner
        uid: 98770fbc-c4ff-4b9d-a7f6-834c6b235798
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            elementCondition: null
            fieldUid: 3a55636c-f114-4ca1-84a3-f568f17a51b0 # Browser title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b139da86-97e8-411a-ae76-0097acc1605e
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 55409bef-f02b-43a6-87ba-6645890db160 # Meta description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 4c7fcb8c-f17c-49e2-bbb0-97ff44f582ce
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 5beb9697-853c-400d-825c-5dc6e8f9707e # No index
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: f7cba193-8102-4d19-9e75-b4196c506d7a
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 49e4be6b-31e8-4637-970f-72b746d0dd07 # OG title override
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a001cba-c15a-4d50-92ea-e75f031a8ed4
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: ac776189-eb45-4663-a943-42e6263a2928 # OG description
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 39330b36-e493-48c1-9704-9b75a148c22f
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 93911dec-d597-4048-be70-3822341db5c8 # OG image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ccd4e25f-ffa4-4474-a872-ffbf05e83326
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 75347aed-7cd3-4a88-a475-d94c64fff91b # OG type
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 55de7d23-3ede-4d8e-9d3e-e75349bacc7c
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 9ba80f98-3521-4d95-8103-833cc54f9074 # Twitter card
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bffb447f-b388-4f2d-9c1e-5654a4b32c61
            userCondition: null
            warning: null
            width: 100
          -
            elementCondition: null
            fieldUid: 096e0833-599f-412d-96d1-e509f94c841e # Twitter creator
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb0054a5-5b4a-470b-82f5-14b4c5fcc89b
            userCondition: null
            warning: null
            width: 100
        name: SEO
        uid: 4a908d80-1cad-4095-9f6d-b296a26c996b
        userCondition: null
handle: homePages
hasTitleField: true
name: 'Home pages'
section: 329fb3c3-eacd-4f5a-8086-8cd96ac705fc # Home pages
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
