baseUrl: $PRIMARY_SITE_URL
enabled: true
handle: default
hasUrls: true
language: en-GB
name: 'Comedy with Romesh'
primary: true
siteGroup: b99e46fe-a420-4fd0-abfc-8eb0989ea429 # Boilerplate
sortOrder: 1
