fieldLayouts:
  091ea649-e7e2-47c7-a4b4-7739b3299df4:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: f825e94a-9acf-4515-9393-dd0e7564ff27
            warning: null
            width: 100
        name: Content
        uid: 7147e423-f696-4e1f-8e3c-e25c6728eac5
fs: downloads
handle: downloads
name: Downloads
sortOrder: 2
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: null
transformSubpath: ''
