columnSuffix: iemhjkff
contentColumnType: text
fieldGroup: 2dcc0933-0db0-4d99-b21d-b7bcfa05c2e1 # Globals
handle: address
instructions: null
name: Address
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 3
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
