columnSuffix: null
contentColumnType: text
fieldGroup: 2dcc0933-0db0-4d99-b21d-b7bcfa05c2e1 # Globals
handle: linkedIn
instructions: 'Full link to your LinkedIn profile'
name: 'Linked In'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
